### ISSUE TITLE
Problem with starting code markers that follow directly after a bracket

### ISSUE THREAD

**Issue by SicroAtGit** [tajmone/ST3-Asciidoctor#4]
I have an AsciiDoc file that contains a code enclosed in code markers (`). Directly before the starting code marker there is a bracket which causes your AsciiDoc package to mark it as an error:

![error](https://user-images.githubusercontent.com/18380976/100514615-93c51200-3176-11eb-8525-42e8d09c8bf5.png)

**Comment by SicroAtGit** [comment]
I just noticed that AsciiDoctor also has problems with this and also does not interpret the starting code marker as such. Then everything is correct and this issue can be closed. But it is still good to have mentioned it here, I think.

**Comment by tajmone** [comment]
The idea of marking the error with a red line is based on the assumption that inline quotes should be on a same line (i.e. not wrapping text in the middle of quote markup), which makes sense since idiomatic AsciiDoc should be wrapped one-sentence-per-line.

But the problem here is that you should be using constrained quotes, due to the special `*` char:

```asciidoc
{nbsp}``*``
```

which is then parsed correctly by the syntax.

Defintely, in the future the syntax should be able to handle better some edge cases and errors, but right now it's too early for some of these, because it's already entangled enough, and too many syntax elements are still either suppressed or not implemented.

The switch from the original ST2 syntax to the new ST3 format is not all that easy, because the new format allows more powerful handling of states, so each element should be basically re-written almost from scratch (although we can salvage most of the original RegExs definitions and scopes namings).

**Comment by tajmone** [comment]
P.S. don't forget that AsciiDoc allows quote markup inside line-code, so unless you use the double ticks (unconstrained) AsciiDoc will assume that the `*` is for marking contents as __stong__.

See:

- [Asciidoctor Manual » §9.2. Unconstrained quotes](https://asciidoctor.org/docs/user-manual/#unconstrained-quotes)

**Comment by SicroAtGit** [comment]
Okay, thanks. I will use the double ticks.
